### ISSUE TITLE
Introduce argument check logics

### ISSUE THREAD

**Issue by tagomoris** [msgpack/msgpack-ruby#105]
Currently method argument checks are not common between CRuby and JRuby.
It's better to have common argument check for better compatibility (ex: io-like object of `Buffer#new` arguments) and throw ArgumentError for invalid values.

But it could break working application code (w/ ignored or danger argument values).
So this change should be done as major or minor version up, not patch version bump.

**Comment by chrisseaton** [comment]
Have you got an examples of incompatibilities?

If not I think I'm likely to close this pretty old issue.
