### ISSUE TITLE
Should not rely on rb_num2int function but NUM2INT macro

### ISSUE THREAD

**Issue by rhertzog** [msgpack/msgpack-ruby#106]
We packaged the latest msgpack release for Kaii and discovered that it failed to build on i386/armel/armhf while it compiles fine on amd64. The failure is related to the absence of the rb_num2int symbol in libruby.

Effectively this function is only available when sizeof(int) < sizeof(long)... however the corresponding macro (NUM2INT) is always available. So please use the macro and not this function.

Cc to @sbrun

**Comment by tagomoris** [comment]
@rhertzog Could you create a pull-request to do that fix?

**Comment by tagomoris** [comment]
I pushed a commit to solve this issue: c74b26600294453b6e2dcd4808ed3ba941fa0212
(I missed to create pull-request for it. oops.)

**Comment by rhertzog** [comment]
Thanks, closing the ticket then.

**Comment by ZeroChaos-** [comment]
Any chance you want to make a tagged release with this fix?

**Comment by tagomoris** [comment]
I've just released `v0.7.5`.

**Comment by ZeroChaos-** [comment]
You are a wonderful human being. Thanks
