### ISSUE TITLE
Inconsistent return value of `#to_msgpack(packer)`

### ISSUE THREAD

**Issue by tagomoris** [msgpack/msgpack-ruby#121]
`#to_msgpack(packer)` returns given packer instance, not msgpack string.
Generally, `#to_x` method returns instance of x in Ruby way. Current behavior is very confusing.

Returning packer is for recursive packing, so we need to add another method for it.
See also: https://github.com/msgpack/msgpack-ruby/pull/116#issuecomment-221475038

What's the best name of that method?

**Comment by khalilfazal** [comment]
`build_msgpacker(packer) #=> packer` sounds good to me.  
No justification other than that it sounds good.  
Anyone have a better idea?
