### ISSUE TITLE
Incorrect encoding on BigDecimal

### ISSUE THREAD

**Issue by phuongnd08** [msgpack/msgpack-ruby#128]
If I encode a float:
```
$ {"n"=>9850500.to_f}.to_msgpack
=> "\x81\xA1n\xCBAb\xC9\xD0\x80\x00\x00\x00"
```

But if I encode the same number as BigDecimal
```
{"n"=>9850500.to_d}.to_msgpack
=> "\x81\xA1n\xC4\t9850500.0"
```

**Comment by phuongnd08** [comment]
This commit fix the issue for me: https://github.com/w1mvy/msgpack-ruby/commit/d738c452f95f6e7fa0d0ee12e75cc7cc718debb9

**Comment by khalilfazal** [comment]
Can you clarify that is meant by #to_d?


    require 'bigdecimal'
    require 'bigdecimal/util'
    require 'msgpack'

    {"n"=>9850500.to_d}.to_msgpack

Gives error:  

    NoMethodError: undefined method `to_msgpack' for 0.98505e7:BigDecimal

**Comment by phuongnd08** [comment]
I'm using Rails. If you open it in a Rails console it should work. to_d mean convert an object to BigDecimal.

**Comment by khalilfazal** [comment]
I understand how [String#to_d](http://apidock.com/ruby/String/to_d) works, but I don't know how you got `#to_msgpack` to work on a BigDecimal without raising a `NoMethodError` exception.

**Comment by phuongnd08** [comment]
I see. Upon closer dig, it is our issue. We defined #to_msgpack over BigDecimal by delegating to String. Fixed now.
