### ISSUE TITLE
Extension type for modules

### ISSUE THREAD

**Issue by christopheraue** [msgpack/msgpack-ruby#131]
Currently, an extension type can only be registered for classes: https://github.com/msgpack/msgpack-ruby/blob/master/ext/msgpack/packer_class.c#L283.

Couldn't modules be allowed as well? Inheritance of ext types works and already checks modules in the ancestor chain: https://github.com/msgpack/msgpack-ruby/blob/master/ext/msgpack/packer_ext_registry.h#L55

I'm looking to accomplish something like this (without inheritance):

```ruby
module Local
  def local_id
    # ...
  end
end

class LocalObject
  include Local
end

pk = MessagePack::Packer.new(io)
pk.register_type(0x01, Local) { |obj| obj.local_id }

obj1 = LocalObject.new
pk.write(obj1)

obj2 = LocalObject.new
pk.write(obj2)
```

And deserializing on a remote machine:

```ruby
class RemoteObject
  def initialize(remote_id)
    # ...
  end
end

uk = MessagePack::Unpacker.new(io)
uk.register_type(0x01) { |remote_id| RemoteObject.new(remote_id) }
```

**Comment by tagomoris** [comment]
It looks reasonable for me.
@christopheraue can you write patches and tests for that update?

**Comment by christopheraue** [comment]
Yes, I'll do that.

**Comment by tagomoris** [comment]
`v1.1.0` has been released with this feature for all platform (including x86/64 & java).
