### ISSUE TITLE
jruby MessagePack::Unpacker is loading all data from stream

### ISSUE THREAD

**Issue by kirillrdy** [msgpack/msgpack-ruby#138]
It looks like mri version of unpacker does buffered reads from the stream when given an io, but jruby version is loading all data from stream into memory.
Example code
```ruby
file = File.new("some_large_file", "rb")
MessagePack::Unpacker.new(file) # in jruby reads all file here
```
I hope this finding at least helps someone

**Comment by chrisseaton** [comment]
Useful information, but closing as not a bug unless someone has an issue with the behaviour.
