### ISSUE TITLE
Cannot install in ruby 2.5.0 in Windows with rubygems

### ISSUE THREAD

**Issue by sohnryang** [msgpack/msgpack-ruby#154]
Log:

```
ERROR:  Error installing msgpack:
        The last version of msgpack (= 1.2.2) to support your Ruby & RubyGems was 1.2.2. Try installing it with `gem install msgpack -v 1.2.2`
        msgpack requires Ruby version < 2.5, >= 1.9. The current ruby version is 2.5.0.
```

**Comment by tagomoris** [comment]
I've merged #153, and released v1.2.3.
Could you try it?

**Comment by fujimotos** [comment]
@tagomoris I checked the windows package of v1.2.3 and found that the package only
contains `msgpack.so` for Ruby 2.0/2.5. So it does not work for other Ruby versions.

I confirm this by the following procedure:

```
$ tar -xf msgpack-1.2.3-x64-mingw32.gem
$ zcat metadata.gz  | grep msgpack.so | less
- lib/msgpack/2.0/msgpack.so
- lib/msgpack/2.5/msgpack.so
```

Apparently, this breaks other project's build system. For example, Fluentd's Windows CI
testing is now failing since it cannot load msgpack on Ruby v2.3.0.

> C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/msgpack-1.2.3-x64-mingw32/lib/msgpack.rb:11:in `require': cannot load such file -- msgpack/msgpack (LoadError)
>
> https://ci.appveyor.com/project/fluent/fluentd/build/2842/job/yex2bvmxpeoexysv

**Comment by tagomoris** [comment]
I've released v1.2.4 again, with confirming the content of files.
```
MBA:hoge tagomoris$ tar xf msgpack-1.2.4-x64-mingw32.gem 
MBA:hoge tagomoris$ gzcat metadata.gz | grep msgpack.so
- lib/msgpack/2.0/msgpack.so
- lib/msgpack/2.1/msgpack.so
- lib/msgpack/2.2/msgpack.so
- lib/msgpack/2.3/msgpack.so
- lib/msgpack/2.4/msgpack.so
- lib/msgpack/2.5/msgpack.so
```
I'm so sorry to release buggy gem.

**Comment by fujimotos** [comment]
Thanks for the swift response!
I can confirm that the Widows package (v1.2.4) is now working with Ruby 2.1-2.4.

Also I tested the package with Ruby 2.5 on `x64-mingw32`, and found it works without
problems too.

**Comment by sohnryang** [comment]
I know it's quite late, but it works!
Thanks!

**Comment by sohnryang** [comment]
I think I can close this issue now.
