### ISSUE TITLE
Any plans on providing a generic object serialization?

### ISSUE THREAD

**Issue by paddor** [msgpack/msgpack-ruby#155]
I'd love to see MsgPack able to be used like `Marshal` or Oj's object mode (`Oj.dump obj, mode: :object`). Are there any plans on supporting that? This has been the main reason keeping me from using MsgPack, and I don't want to convert my objects to Hashes before serialization / convert from Hashes after deserialization.

**Comment by tagomoris** [comment]
No. That's not thing of msgpack.
