### ISSUE TITLE
Issue with difference in size of message Pack based on different language

### ISSUE THREAD

**Issue by Rahul-Sharma-87** [msgpack/msgpack-ruby#156]
Hi,

I m facing issue where same message **Packed** with the ruby and C# has different number of bytes and where ruby code msgpack library gives below warning while unpacking:
Error in processing message. error_class=MessagePack::MalformedFormatError error=#### <MessagePack::MalformedFormatError: 11 extra bytes after the deserialized object>

My intention is to send data from c# to ruby program.

Message in ruby: [works fine]
["test3.aa",time,{"a"=>1}].to_msgpack

Message in C# [Shows warning message for extra bytes on unpack]
Object[] test1 = new Object[3] {"test3.aa", 1308466941, new {a =1}};

Thanks in advance,
Rahul

**Comment by tagomoris** [comment]
Let me close this because there are no additional information here and https://github.com/msgpack/msgpack-cli/issues/290
Please reopen this if it still is.
