### ISSUE TITLE
cant install msgpack ob ubuntu 18.04

### ISSUE THREAD

**Issue by Mahagon** [msgpack/msgpack-ruby#175]
Hey :),

i am currently trying to install msgpack 1.3.1 for a test environment.

* puppetserver 6.7.2
* ubuntu/bionic64 vagrant image

I cant figure out why i get this error, so i hope you guys can help me

>!

    /opt/puppetlabs/puppet/lib/ruby$ sudo /opt/puppetlabs/puppet/bin/gem install msgpack
    Building native extensions. This could take a while...
    ERROR:  Error installing msgpack:
            ERROR: Failed to build gem native extension.
    
        current directory: /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/msgpack-1.3.1/ext/msgpack
    /opt/puppetlabs/puppet/bin/ruby -r ./siteconf20200109-2480-1gbvk22.rb extconf.rb
    checking for ruby/st.h... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.
    
    Provided configuration options:
            --with-opt-dir
            --with-opt-include
            --without-opt-include=${opt-dir}/include
            --with-opt-lib
            --without-opt-lib=${opt-dir}/lib
            --with-make-prog
            --without-make-prog
            --srcdir=.
            --curdir
            --ruby=/opt/puppetlabs/puppet/bin/$(RUBY_BASE_NAME)
    /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:590:in `try_cpp'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:1098:in `block in have_header'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:948:in `block in checking_for'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:350:in `block (2 levels) in postpone'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:320:in `open'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:350:in `block in postpone'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:320:in `open'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:346:in `postpone'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:947:in `checking_for'
            from /opt/puppetlabs/puppet/lib/ruby/2.5.0/mkmf.rb:1097:in `have_header'
            from extconf.rb:3:in `<main>'
    
    To see why this extension failed to compile, please check the mkmf.log which can be found here:
    
      /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/msgpack-1.3.1/mkmf.log
    
    extconf failed, exit code 1
    
    Gem files will remain installed in /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/gems/msgpack-1.3.1 for inspection.
    Results logged to /opt/puppetlabs/puppet/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/msgpack-1.3.1/gem_make.out

&#x200B;

!<

i already tried to install an older version
    sudo /opt/puppetlabs/puppet/bin/gem install msgpack --version 1.2.0
but that also failed with the same error.

same if i install ruby-dev on a ubuntu 18.04 vagrant image.

am i missing something?

**Comment by tagomoris** [comment]
The message explains to see `mkmf.log`, and previous message also says:
```
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

See your logs to find missing something.

**Comment by Mahagon** [comment]
the packeges **gcc make** and **rubygems**
thx for the help
