### ISSUE TITLE
non-executable scripts in bench

### ISSUE THREAD

**Issue by pvalena** [msgpack/msgpack-ruby#176]
In version 1.3.1, there are 3 `bench/run*.sh` scripts, that are missing executable bit, but there is `#!/bin/sh`.

**Comment by tagomoris** [comment]
Those files are for users who want to run benchmarks in their environments.
I don't think it's a problem, but reopen this if it is.

**Comment by pvalena** [comment]
This was supposed to be RFE. IMHO the files should either have executable bit (`chmod +x`) added, or the `#!/bin/sh` removed. It's an inconsistency, and therefore flagged by linter on Fedora.
