### ISSUE TITLE
Should I be able to serialize class objects?

### ISSUE THREAD

**Issue by jongbeau** [msgpack/msgpack-ruby#181]
I have a complex class object.  When I run `MessagePack::Packer.new(obj))`, I get `NoMethodError: undefined method `to_msgpack' for #<MyModule::MyClass:0x00007feb3662e548>`.

**Comment by tagomoris** [comment]
Read the document about [extension types](https://github.com/msgpack/msgpack-ruby#extension-types). That shows how to serialize/deserialize objects of your own classes.
