### ISSUE TITLE
Async buffer safety

### ISSUE THREAD

**Issue by ioquatix** [msgpack/msgpack-ruby#187]
Hello.

I'd like to check if msgpack should be safe to use with async.

i.e. 

```
# peer is Async::IO::Socket
# wrapper is Wrapper < MessagePack::Factory
packer = wrapper.packer(peer)
unpacker = wrapper.unpacker(peer)
```

It would be great to make an official position and some examples.

**Comment by tagomoris** [comment]
Packer/Unpacker receive the IO-like object but we don't test behaviors with Async::IO objects now.
Packer will never call `#close_write`, and Unpacker can't handle read timeouts correctly.

Typically, we'll use the `Unpacker#feed_each` method with async I/O sockets, like below:
```ruby
unpacker = MessagePack::Factory.unpacker
while data = peer.read
  unpacker.feed_each{|obj| process(obj) }
end
```
We can see the actual/working example on [Fluentd code](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_forward.rb#L246-L272) (it uses `cool-io`, though).

**Comment by ioquatix** [comment]
Inverted flow control is not easy to deal with.

I tried it and it seems to work okay.

`Async::IO` will behave like normal IO object.

It called `Fiber.yield` when the operation would block.

**Comment by tagomoris** [comment]
If we should say the answer officially, it'll be "We don't test it, so corner cases may cause something wrong".
Requirements on argument io objects are to respond `#write` (or `#append`) and `#readpartial` (or `#read`) as documented [here](http://ruby.msgpack.org/MessagePack/Packer.html#initialize-instance_method) and [here](http://ruby.msgpack.org/MessagePack/Unpacker.html#initialize-instance_method), so `Async::IO` objects may be able to work well with Packer/Unpacker, but we're not sure.

It should be a good enhancement to add tests on those async IOs when it's supported by Ruby core.

**Comment by ioquatix** [comment]
Thanks for pointing me at the documentation. Those methods are supported so it should be fine. I found that documentation hard to find/locate, I ended up looking through the C source code to try and figure out the required interface.

The only part that was tricky for me was I didn't know to call `packer.flush`. Is this documented?

**Comment by ioquatix** [comment]
```
 0.17s    error: Async::Task [oid=0x3e8] [pid=228918] [2020-06-11 19:20:11 +1200]
               |   EOFError: IO reached end of file
               |   → /home/samuel/Documents/socketry/async-container/examples/queue/server.rb:82 in `read'
               |     /home/samuel/Documents/socketry/async-container/examples/queue/server.rb:82 in `block (3 levels) in <main>'
               |     /home/samuel/.gem/ruby/2.7.1/gems/async-io-1.30.0/lib/async/io/socket.rb:145 in `connect'
               |     /home/samuel/.gem/ruby/2.7.1/gems/async-io-1.30.0/lib/async/io/address_endpoint.rb:51 in `connect'
               |     /home/samuel/Documents/socketry/async-container/examples/queue/server.rb:73 in `block (2 levels) in <main>'
               |     /home/samuel/.gem/ruby/2.7.1/gems/async-1.26.1/lib/async/task.rb:258 in `block in make_fiber'
```

This is coming out of unpacker.read when the internal socket is closed.

I assume this is normal? Ruby sometimes throws weird exceptions and I guess you can transit nil through the msgpack stream, so returning nil wouldn't be good enough.

**Comment by tagomoris** [comment]
> The only part that was tricky for me was I didn't know to call packer.flush. Is this documented?

We can see the example that does it in "Streaming serialization" section: http://ruby.msgpack.org/

> I assume this is normal?

That's true. We need to rescue `EOFError` when we use the `#read` method with the `io` argument. Returning `nil` is not expected by any users as you wrote.
`Unpacker#each` doesn't have such a problem, I think.

**Comment by ioquatix** [comment]
> Unpacker#each doesn't have such a problem, I think.

I confirmed this in my own code.

**Comment by ioquatix** [comment]
FYI here is my code that I was messing around with today: https://github.com/socketry/async-container/blob/master/examples/queue/server.rb

**Comment by ioquatix** [comment]
My original request is satisfied by the links to the documentation, thanks for your help.
