### ISSUE TITLE
Date/Time Not actually in UTC

### ISSUE THREAD

**Issue by skizot722** [msgpack/msgpack-ruby#19]
During packing, datetime/time fields are not actually being converted to UTC.

1.9.3p429 :099 > MessagePack.unpack(MessagePack.pack(MyThing.find(38432).serializable_hash))['created_at']
  MyThing Load (0.9ms)  SELECT "my_things".* FROM "my_things" WHERE "my_things"."id" = $1 LIMIT 1  [["id", 38432]]
 => "Time[2013-08-22 16:59:20 UTC]" 

1.9.3p429 :100 > MyThing.find(38432).created_at
  MyThing Load (0.9ms)  SELECT "my_things".* FROM "my_things" WHERE "my_things"."id" = $1 LIMIT 1  [["id", 38432]]
 => Thu, 22 Aug 2013 16:59:20 CDT -05:00 

Table "public.my_things"
 id           | integer                     | not null default nextval('my_things_id_seq'::regclass)
 created_at   | timestamp without time zone | not null
 updated_at   | timestamp without time zone | not null

The first command that pack's and unpack's should show "2013-08-22 21:59:20 UTC", yet it shows "2013-08-22 16:59:20 UTC".  When packing, it should be calling .utc() on the date, and it's not.  Any ideas?

**Comment by cosmo0920** [comment]
Time serialization/deserialization is not supported current msgpack.
This feature will be supported by ext types of version v0.7.x.

Related to PR #90 discussions.

**Comment by tagomoris** [comment]
Now msgpack-ruby v0.7 supports ext types. So you can serialize Time (or Date) by code like below:
```ruby
MessagePack::DefaultFactory.register_type(0x01, Time, packer: ->(t){ t.to_i.to_msgpack }, unpacker: ->(d){ Time.at(MessagePack.unpack(d)) })
t = Time.now
packed_time = MessagePack.pack(t)
MessagePack.unpack(packed_time) #=> 2015-11-08 13:33:59 +0900
```
