### ISSUE TITLE
Gems installed as root don't get the so file moved into the lib/msgpack folder

### ISSUE THREAD

**Issue by 6wl** [msgpack/msgpack-ruby#20]
System: Linux, Fedora 19

Steps:-
  - As root, 'gem install msgpack'
  - When finished, start irb and require 'msgpack'

Results:-
  - Will fail with message
'LoadError: cannot load such file -- /usr/local/share/gems/gems/msgpack-0.5.5/lib/msgpack/msgpack'

Expected:-
  - Looks like when installing a gem as root, it doesn't copy the .so file into the /lib/msgpack/ folder.

Notes:-
  - Does correctly copy that file when using a standard user, but I try and install gems as the root user, when they are going to be used system wide.

**Comment by tagomoris** [comment]
This issue is already solved at `v0.5.6`. Please reopen if any problems still exist.
