### ISSUE TITLE
Fail fetching v 1.4.1

### ISSUE THREAD

**Issue by fabiensebban** [msgpack/msgpack-ruby#208]
Since today, version 1.4.1 cannot be found to be downloaded. So I can't run `bundle install` if my environment (actually using docker containers) did not previously download this version.

Here is the error message:

```
Your bundle is locked to msgpack (1.4.1), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of
msgpack (1.4.1) has removed it. You'll need to update your bundle to a version other than msgpack (1.4.1) that hasn't been removed in order to install.
```

To solve the problem I had to `bundle update` to get the 1.4.2 version. I just post this issue here in case someone has the same error.

**Comment by tagomoris** [comment]
I yanked `1.4.1` to resolve the problem of #207.
Please update your locked dependency to `1.4.2`. Thank you for your patience.

**Comment by fabiensebban** [comment]
Sorry @tagomoris , I did not see this issue.
I close this one.
