### ISSUE TITLE
missing 1.4.2-x64-mingw32 on rubygems.org

### ISSUE THREAD

**Issue by xtalkme** [msgpack/msgpack-ruby#214]
Hello,

It seems that 1.4.2-x64-mingw32 is missing on [rubygems.org](https://rubygems.org/gems/msgpack/versions).
Not sure this is intended, but it creates issues with installing fluent-logger, due to dependency "msgpack >= 1.0.0, < 2"
Also not sure this is the right place, in case it is not, my bad.

Thanks in advance!

**Comment by tagomoris** [comment]
Recently, we're trying to [stop supporting fat gems](https://github.com/msgpack/msgpack-ruby/pull/193) to reduce the maintenance cost of this library. It's supposing that most Windows Ruby runtime environments have compilers for native libraries that can build msgpack (without `-mingw` suffix) gems.
But if you've seen error messages, our assumption may be incorrect.
@xtalkme What's the environment you're using? How do you install Ruby runtime?

**Comment by xtalkme** [comment]
@tagomoris Thanks for your help.
I am by no means an expert on this subject, ill do my best to explain our use case.

We run into these errors when we use the puppet agent's (6.4.2) built-in Ruby 2.5 version. (Old)
When I install the 2.5.8 with the devkit, I'm able to build the package.
I will test this with a more recent version of the puppet agent and let you know the results.

**Comment by xtalkme** [comment]
@tagomoris we get the same error running the latest puppet agent version.
(You have to install development tools first.)
Installing msgpack version 1.3.3 works fine with this ruby environment.

**Comment by tagomoris** [comment]
@xtalkme Yes, installing development tools is the key requirement for msgpack-ruby 1.4 or later. I want to keep it if there seem no serious blockers.

**Comment by tagomoris** [comment]
Let me close this issue. Please reopen this or create another if there still be problems.
