### ISSUE TITLE
Apple M1 error: cannot load such file -- msgpack

### ISSUE THREAD

**Issue by messutied** [msgpack/msgpack-ruby#215]
Getting the following error in Apple M1 Macbook Pro:

```
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- msgpack (LoadError)
	6: from -e:1:in `<main>'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	2: from /Library/Ruby/Gems/2.6.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.bundle - /Library/Ruby/Gems/2.6.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.bundle (LoadError)
```

Found a relevant closed ticket https://github.com/msgpack/msgpack-ruby/issues/195 but their instructions are not clear, some clarification would be highly appreciated.

**Comment by tagomoris** [comment]
You may have a msgpack binary under `/Library/Ruby/Gems/2.6.0/gems/` with arch name (arm). If so, rubygem may be able to find it by removing the problematic binary which is causing the current error (`/Library/Ruby/Gems/2.6.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.bundle`).

JFYI: I'm running Ruby & msgpack-ruby on my M1 mac by building/installing my own Ruby runtime, not system ruby :D

**Comment by messutied** [comment]
Thanks for the JFYI! Realized I was still using system ruby even though I had installed it through homebrew, adding homebrew's to my path to enable it solved the issue, so closing this ticket.

**Comment by luzanto** [comment]
Hi @messutied, I'm having the same problem. Could you explain which steps did you follow to solve the issue? I would really appreciate your answer =)

**Comment by messutied** [comment]
Hi @luzanto, using ruby from Homebrew is what solved the issue for me, I had already installed it, I just needed to include it in my path, I ran `brew info ruby` and there I found instructions on how to do that.

```
If you need to have ruby first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc
```

Instructions might be different for you, I suggest you try with `brew info ruby` too.
