### ISSUE TITLE
Release latest version with fix for JRuby 9.3?

### ISSUE THREAD

**Issue by ivoanjo** [msgpack/msgpack-ruby#231]
Howdy!

I came here because I got bitten by #226 . I was glad to see that it was fixed, but I'd like to ask for a release including that fix, as otherwise it's really awkward to use, since because of the native bits, one can't just consume the git version of this gem.

Thanks again for all your awesome work on msgpack, and on supporting JRuby :)

**Comment by tagomoris** [comment]
Now I have a problem about running JRuby on my laptop - it's the barrier about the release :(
https://github.com/msgpack/msgpack-ruby/pull/225#issuecomment-941911143

**Comment by prakhunov** [comment]
Just curiousy if there are any updates on cutting a new release ?

**Comment by ivoanjo** [comment]
Looks like support for macOS ARM is now in the latest snapshot builds: https://twitter.com/headius/status/1479188425660149761 .

**Comment by prakhunov** [comment]
> 

Yup I don't even think that support is necessary, looks like JRuby 9.3.2.0 fixed the issues of it not running at all.

https://github.com/jnr/jffi/pull/116
https://github.com/jnr/jnr-ffi/issues/257

**Comment by ahorek** [comment]
@tagomoris try it out https://www.jruby.org/2022/01/19/jruby-9-3-3-0.html or let us know if you have any issues, thanks!

**Comment by tagomoris** [comment]
I've just released `v1.4.3`.
Thank you @ivoanjo for pinging me and @ahorek for the comment about jruby 9.3.3.0!

**Comment by ivoanjo** [comment]
Thank you for the awesome work on msgpack! :)
