### ISSUE TITLE
msgpack-ruby-master: bundle fatal: Not a git repository (or any parent up to mount point)

### ISSUE THREAD

**Issue by dmitriklein** [msgpack/msgpack-ruby#232]
cd msgpack-ruby-master

-bash-3.2$ bundle
fatal: Not a git repository (or any parent up to mount point /export0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /export0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
-bash-3.2$

**Comment by tagomoris** [comment]
It's not a msgpack-ruby problem, but your environment (or usage of git/bundler).
