### ISSUE TITLE
gem install msgpack-1.3.3.gem generates make: Fatal error: Command failed for target `buffer.o'

### ISSUE THREAD

**Issue by dmitriklein** [msgpack/msgpack-ruby#233]
gem install msgpack-1.3.3.gem --debug

...
Exception NoMethodError' at /opt/csw/lib/ruby/2.0.0/rubygems/package.rb:420 - undefined methodreadpartial' for #Gem::Package::TarReader::Entry:0x877f634

...
Exception Errno::ENOENT' at /opt/csw/lib/ruby/2.0.0/fileutils.rb:1439 - No such file or directory - /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/spec/spec_helper.rb
...
ExceptionErrno::ENOENT' at /opt/csw/lib/ruby/2.0.0/fileutils.rb:1319 - No such file or directory - /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/spec/timestamp_spec.rb
...
Exception NoMethodError' at /opt/csw/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:71 - undefined methodseek' for #Zlib::GzipReader:0x859f79c
...

ERROR: Error installing msgpack-1.3.3.gem:
ERROR: Failed to build gem native extension.
...

make "DESTDIR="
compiling buffer.c
cc: -W option with unknown program all
*** Error code 1
The following command caused the error:
/opt/SUNWspro/bin/cc -I. -I/opt/csw/include/ruby-2.0.0/i386-solaris2.10 -I/opt/csw/include/ruby-2.0.0/ruby/backward -I/opt/csw/include/ruby-2.0.0 -I. -DHAVE_RUBY_ST_H -DHAVE_ST_H -DHAVE_RB_STR_REPLACE -DHAVE_RB_INTERN_STR -DHAVE_RB_STR_INTERN -DHAVE_RB_BLOCK_LAMBDA -DHAVE_RB_HASH_DUP -DHAVE_RB_HASH_CLEAR -I/opt/csw/include -D_FILE_OFFSET_BITS=64 -KPIC -xO3 -xarch=pentium_pro -xchip=pentium_pro -KPIC -I.. -Wall -O3 -g -std=gnu99 -m32 -o buffer.o -c buffer.c
make: Fatal error: Command failed for target `buffer.o'

**Comment by tagomoris** [comment]
Are you using Ruby 2.0.0? It's completely outdated.
Use newer Ruby version and msgpack-ruby.
