### ISSUE TITLE
Installing msgpack-ruby on Solaris 10: fatal: Not a git repository

### ISSUE THREAD

**Issue by dmitriklein** [msgpack/msgpack-ruby#234]
-bash-3.2$ pwd
/export0/home/telegraf/fluentd/msgpack/msgpack-ruby-master
-bash-3.2$ bundle
fatal: Not a git repository (or any parent up to mount point /export0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /export0)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/

**Comment by tagomoris** [comment]
It's not a msgpack problem, but your environmental issue about network connectivity. 
Read those messages carefully.
