### ISSUE TITLE
Allow to register native types as extensions

### ISSUE THREAD

**Issue by casperisfine** [msgpack/msgpack-ruby#243]
Related: https://github.com/msgpack/msgpack-ruby/issues/57
Ref: https://github.com/msgpack/msgpack/issues/206

The message pack spec doesn't have support for big nums, which sometimes cause issues when serializing arbitrary data.

It would be nice if we could register a custom type for `Integer`, that would be called when the number is too big, e.g. something like:

```ruby
require 'msgpack'

factory = MessagePack::Factory.new
factory.register_type(
  0x42,
  Integer,
  packer: ->(int) { int.to_s },
  unpacker: -> (payload) { Integer(payload) }
)

factory.dump(42) # Use the native integer type
factory.dump(2**400) # Use the registered packer
```

**Comment by tagomoris** [comment]
I'm not positive to support this feature because `Integer` objects will be packed into 2 (or more?) different msgpack types. It seems too complicated for users. It will happen if the value is too big for `unsigned long long`. What will happen if we register `Float`?
@casperisfine Do you have any use cases other than `Integer`?

**Comment by tagomoris** [comment]
And an idea comes up: we may be able to solve the problem of too big `Integer` by overriding `Integer#to_msgpack_with_packer` method (defined [here](to_msgpack_with_packer(packer))).
This method will just call `packer#write_int` method. We can call `packer#write_ext` in `rescue RangeError` instead.

Yes, it is a little hacky. But IMO it's better to contain this code in this gem as an opt-in module than introducing many complex code on ext type mechanism only for Integer (if there are no other use cases).

The pseudo code is (I don't try to run it):
```ruby
class TooBigInteger
  def initialize(int)
    @int = int
  end
  def to_s
    @int.to_s
  end
end

factory.regsiter_type(0x42, TooBigInteger, packer: ->(obj){ obj.to_s }, unpacker: ->(payload){ Integer(payload) })
class Integer
  private
  def to_msgpack_with_packer(packer)
    packer.write_int self
    packer
  rescue RangeError
    packer.write_ext TooBigInteger(self)
    packer
  end
end
```

**Comment by casperisfine** [comment]
> It seems too complicated for users

I don't think most users would really be concerned about the serialization format. Usually when you use msgpack extensions it's because you are both producer and consumer, so "complexity" of the format doesn't really enter into account. 

> What will happen if we register Float?

Likely nothing, as Float would always fit? Maybe you'd prefer some more explicit `register_bigint` kind of API?

> by overriding Integer#to_msgpack_with_packer method

My problem with the `to_msgpack*` methods, is that there can be only one, so it's not really composable.

I'm also worried having to call back into a Ruby method for every single integer might tank performance.

But if you are certain about this choice, I can implement it.

**Comment by casperisfine** [comment]
By the way, we already kinda have this behavior for `String / Array / Hash` subclasses:

```c
    case T_STRING:
        if(rb_class_of(v) == rb_cString || !msgpack_packer_try_write_with_ext_type_lookup(pk, v)) {
            msgpack_packer_write_string_value(pk, v);
        }
        break;
    case T_ARRAY:
        if(rb_class_of(v) == rb_cArray || !msgpack_packer_try_write_with_ext_type_lookup(pk, v)) {
            msgpack_packer_write_array_value(pk, v);
        }
        break;
    case T_HASH:
        if(rb_class_of(v) == rb_cHash || !msgpack_packer_try_write_with_ext_type_lookup(pk, v)) {
            msgpack_packer_write_hash_value(pk, v);
        }
        break;
```

I know considering `bigint` as a subclass of `Integer` is a bit of a stretch, but conceptually it makes sense to me.

**Comment by tagomoris** [comment]
I know the behavior about `String` / `Array` / `Hash` subclasses. I would be ok too if Ruby still has `Bignum` class... 🤔 

> My problem with the to_msgpack* methods, is that there can be only one, so it's not really composable.
> I'm also worried having to call back into a Ruby method for every single integer might tank performance.

Performance doesn't matter. Packer/Unpacker is already calling Ruby methods for every single integer after https://github.com/msgpack/msgpack-ruby/pull/135
Defining methods globally is actually a problem. Hmm...

Options (`(...)` is my current feeling):
* Allow registering native types as extensions (looks too much only for Integer)
* Add opt-in core-ext to handle bignum ("global" change is not a good manner)
* Add a specific option to handle bignum (we already have it for symbols. why not? do we add many more similar things in the future?)

Let me think about it in short. Please ping me if I'll be absent for a long time.

**Comment by tagomoris** [comment]
There's a very long thread https://github.com/msgpack/msgpack/issues/206

**Comment by casperisfine** [comment]
Hum, this discussion didn't seem to go anywhere :/

**Comment by casperisfine** [comment]
> Packer/Unpacker is already calling Ruby methods for every single integer after https://github.com/msgpack/msgpack-ruby/pull/135

I'm not sure I follow. `MessagePack.dump(42)` won't call `Integer#to_msgpack`.

**Comment by tagomoris** [comment]
My current preferable idea is:
> Add a specific option to handle bignum

Because:
* We don't have any other use cases of registering native types as extensions except for Integer
* Adding a generic feature for a specific use case is a bad idea
  * Users may use it in a wrong way
  * We need to maintain a very generic feature (and complex code) for a specific use case (and many wrong ways)
* We'll be able to update a specific feature in the future without incompatibilities
  * to use a generic feature (registering native types as extensions) if we will add it in the future

@casperisfine What do you think?

**Comment by casperisfine** [comment]
> My current preferable idea is Add a specific option to handle bignum

To be fair I'm trying to think of other native types potentially impacted by this, but I don't think there's any. I don't think Ruby Float could possibly overflow.

So yes, I'm ok with this, how do you see the interface? Something like:

 - `register_type(-42, Integer, bigint: true)`?
 -  `register_bigint_type(-42, ...)`?

**Comment by tagomoris** [comment]
> * `register_type(-42, Integer, bigint: true)`

This looks good because we already have the `optimized_symbols_parsing` option only for `Symbol`. We'll be able to follow its way.
So, my request is: the option name should be long and descriptive.

**Comment by casperisfine** [comment]
> So, my request is: the option name should be long and descriptive.

Absolutely, I just wasn't very inspired yesterday.

What about `oversized_integer_extension: true` ?

**Comment by tagomoris** [comment]
LGTM > `oversized_integer_extension`
