### ISSUE TITLE
Documentation of symbolize_keys?

### ISSUE THREAD

**Issue by maasha** [msgpack/msgpack-ruby#27]
How does symbolize_keys work with serialization?

**Comment by tagomoris** [comment]
`symbolize_keys` is just ignored for serialization. It's the option for deserialization.

**Comment by maasha** [comment]
Well, it is undocumented for deserialization then.

**Comment by tagomoris** [comment]
See "supported options" of "Constructor Details": http://ruby.msgpack.org/MessagePack/Unpacker.html
