### ISSUE TITLE
Unpack "end of buffer reached" error on Windows

### ISSUE THREAD

**Issue by shorowit** [msgpack/msgpack-ruby#278]
I'm using v1.4.2 w/ ruby 2.7.2 and have software that is trying to read msgpack files produced by a different application.

On Linux, all of the msgpack files are unpacked successfully, while on Windows, some msgpack files are successfully unpacked while others produce an "end of buffer reached" error. It is 100% reproducible.

I am unpacking the msgpack files like so:
```
require 'msgpack'
MessagePack.unpack(File.read('foo.msgpack'))
```

[This file](https://github.com/msgpack/msgpack-ruby/files/8547617/eplusout_runperiod.zip) is unpacked successfully on both Windows and Linux.

[This file](https://github.com/msgpack/msgpack-ruby/files/8547618/eplusout_monthly.zip) is unpacked successfully on Linux but gives an error on Windows:

```
end of buffer reached in :/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:33:in `full_unpack'
:/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:33:in `load'
```

**Comment by jmarrec** [comment]
I can reproduce the error on windows (and success on linux) with msgpack-1.5.1 as well.

**Comment by shorowit** [comment]
One more datapoint: I was able to load both msgpack files in [this online tool](https://toolslick.com/conversion/data/messagepack-to-json) (after first [converting to Base64](https://base64.guru/converter/encode/file)). Since it works using this online tool and works on Linux, I assume the problem is with msgpack-ruby and not the msgpack file itself.

**Comment by tagomoris** [comment]
I can't investigate it because I don't have Windows environments.
Can anyone make a minimized problematic data or dig this problem?

**Comment by jmarrec** [comment]
Here's a MCVE:

eplusout_monthly.json:

```json
{
  "Rows": [
    {
      "12/31 24:00:00": [
        1.4345430107526858,
        -2.7386621001891442,
        48.818548387096776,
        3.188172043010719,
        28.797043010752688,
        167.9233870967742,
        37359955.16355381,
        465295777.160931,
        12121988.592679953,
        33091113.167618275,
        10295417.357381081,
        31319462.646576993,
        166331289.7441193,
        0.0,
        0.0,
        937464611.0997573,
        216204449.56423804,
        0.0,
        161042592.09146383,
        301728898.2797351,
        0.0,
        101460279.55122219,
        -68321276.28048232,
        0.0,
        803544966.4061267,
        774032894.7313985,
        106794387.63326761,
        1480671298.1222599,
        128677038.42529744,
        390554374.6796022,
        0.0,
        0.0,
        295138067.59645236,
        -28842723.32480216,
        958457970.4355736,
        0.0,
        96148456.88343465,
        0.0,
        880594078.3895023,
        -2232796292.6807303,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        3674283751.156255,
        0.0,
        0.016495396224081624,
        0.001968194444444446,
        0.0,
        0.0,
        4.01208270826541,
        18.410901160895314,
        20.420624526399937,
        920482039.0535275,
        3902880749.2107673,
        0.0,
        3.7932995487253818,
        0.8704456601187615,
        0.44030446935555784,
        0.35192125389081386,
        -58924261.99601754,
        979194156.8551725,
        0.0,
        0.0,
        117180000.0
      ]
    }
  ]
}
```

test.rb

```ruby
require 'json'
require 'msgpack'
p = 'eplusout_monthly.json'
data = JSON.parse(File.open(p).read())
pack = MessagePack.pack(data)
File.open('repacked2.msgpack', 'wb') do |f|
  f.puts(pack)
end
MessagePack.unpack(File.read('repacked2.msgpack'))
```

```shell
ruby .\test.rb
Traceback (most recent call last):
        2: from ./test.rb:9:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/msgpack-1.5.1/lib/msgpack.rb:31:in `load'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/msgpack-1.5.1/lib/msgpack.rb:31:in `full_unpack': end of buffer reached (EOFError)
```

**Comment by jmarrec** [comment]
Actually, this is enough:

```json
{
  "something": [
    295138067.59645236
  ]
}
```

**Comment by jmarrec** [comment]
One liner MCVE:

`ruby -e "require 'msgpack'; File.write('repacked2.msgpack', MessagePack.pack([295138067.59645236])); MessagePack.unpack(File.read('repacked2.msgpack'))"`

**Comment by jmarrec** [comment]
Here's a github actions run where I use that one liner, as you can see it works on mac and ubuntu, but not on windows: https://github.com/jmarrec/test-Github-Actions/runs/6211912904?check_suite_focus=true

**Comment by tagomoris** [comment]
I'm guessing that text mode file I/O is tweaking bytes of msgpack on Windows. 
How does it work if you specify binary mode I/O explicitly?

**Comment by jmarrec** [comment]
@tagomoris 

```ruby
ruby -e "require 'msgpack'
File.write('repacked2.msgpack', MessagePack.pack([295138067.59645236]))
- MessagePack.unpack(File.read('repacked2.msgpack'))"
+ MessagePack.unpack(File.read('repacked2.msgpack', mode: 'rb'))"
```

That works indeed.

**Comment by shorowit** [comment]
> I'm guessing that text mode file I/O is tweaking bytes of msgpack on Windows. How does it work if you specify binary mode I/O explicitly?

Confirmed that using `mode: 'rb'` works for me. Thank you, @tagomoris!

**Comment by tagomoris** [comment]
MessagePack is a binary serialization format, and it's obvious that we need to read/write binary data. So, for now, we don't have any good place to be updated.
@jmarrec @shorowit Please send us a pull request if you find it.

**Comment by jmarrec** [comment]
Haha, it wasn't _that_ obvious to us at least given this issue :D 

I have proposed a README.md update in #280 which would make it explicit by adding just two lines
