### ISSUE TITLE
Merge with msgpack-jruby

### ISSUE THREAD

**Issue by minad** [msgpack/msgpack-ruby#3]
See https://github.com/iconara/msgpack-jruby/issues/3

**Comment by tagomoris** [comment]
#47 merged.

**Comment by funny-falcon** [comment]
Is there any chance that Unpacker api will be compatible? I talk about `#read_map_header`, `#read_array_header`, `#read` methods, ability to check buffer, ability to iterate over input stream. It looks like there is no such abilities at the moment.

**Comment by tagomoris** [comment]
More APIs will be supported in JRuby, for more compatibility.
@funny-falcon Could you open another issue for Unpacker api? (or pull-request? :-)

@frsyuki  I think that this issue is to be closed now.
