### ISSUE TITLE
undefined method `to_msgpack' for BigDecimal (NoMethodError)

### ISSUE THREAD

**Issue by collimarco** [msgpack/msgpack-ruby#340]
I am converting some JSON files to msgpack with this code:

```
  File.open("example.msgpack", 'wb') do |output_file|
    Oj.load_file("example.log") do |json|
      msgpack = MessagePack.pack(json)
      output_file.write(msgpack)
    end
  end
```

The problem is that I get this error:

```
/ruby/gems/3.2.0/gems/msgpack-1.7.1/lib/msgpack.rb:41:in `write': undefined method `to_msgpack' for 0.12818649802057203e0:BigDecimal (NoMethodError)

    packer.write v
```

Is there any solution to this problem?
How would you convert a normal JSON lines file to msgpack?

(I don't mind if BigDecimal is rounded to a lower precision)

**Comment by collimarco** [comment]
Found this workaround:

```
class BigDecimal
  def to_msgpack(*args)
    to_f.to_msgpack(*args)
  end
end
```

Maybe should be added to this gem?

**Comment by cmer** [comment]
What's the actual recommended and safe way to pack BigDecimal? Thanks!

**Comment by byroot** [comment]
https://github.com/Shopify/paquito/blob/8423314d08844163f036fdf0aca6f6973d770306/lib/paquito/types.rb#L284-L288
