### ISSUE TITLE
Pass empty string into MessagePack::Unpacker.feed will stop further feeding valid string in version >= 1.7.0

### ISSUE THREAD

**Issue by tung-vu-td** [msgpack/msgpack-ruby#345]
Hi,

Not sure this is a bug, but at least it is a difference between version 1.6.1 and 1.7.0. I figured you guys may want to know.

So if you run the following code, it will output empty array:
```
gem 'msgpack', '= 1.7.0'
require 'msgpack'
require 'stringio'

def test_string()
  s = StringIO.new(String.new)
  pk = MessagePack::Packer.new(s)
  pk.write('hello').write('world').flush
  s.string
end

result = []
unpacker = MessagePack::Unpacker.new
unpacker.feed("")
unpacker.feed(test_string)
unpacker.each do |row|
  result << row
end

puts "#{result}"
```

While changing the first line to `gem 'msgpack', '= 1.6.1'`. The output will be `["hello", "world"]`

**Comment by casperisfine** [comment]
Thanks, that indeed look like a regression, I'll fix it soon, shouldn't be too hard.
