### ISSUE TITLE
LoadError on Windows + Ruby 2.1

### ISSUE THREAD

**Issue by okahashi117** [msgpack/msgpack-ruby#38]
I got LoadError on Windows + Ruby 2.1

``` 
C:\>gem install msgpack
Fetching: msgpack-0.5.8-x86-mingw32.gem (100%)
Successfully installed msgpack-0.5.8-x86-mingw32
Parsing documentation for msgpack-0.5.8-x86-mingw32
Installing ri documentation for msgpack-0.5.8-x86-mingw32
Done installing documentation for msgpack after 0 seconds
1 gem installed

C:\>irb
DL is deprecated, please use Fiddle
irb(main):001:0> require 'msgpack'
LoadError: cannot load such file -- msgpack/msgpack
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/msgpack-0.5.8-x86-mingw32/lib/msgpack.rb:5:in `rescue in <top (required)>'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/msgpack-0.5.8-x86-mingw32/lib/msgpack.rb:2:in `<top (required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):1
        from C:/Ruby21/bin/irb:11:in `<main>'
irb(main):002:0>
```

Problem does not occur on Ruby 1.9 and 2.0.
I can avoid it using 'gem install msgpack --platform=ruby'. 
ffi also had a same problem but it has been fixed a couple of days ago.
This issue could be your help.

> https://github.com/ffi/ffi/issues/368

Thank you.

**Comment by nahi** [comment]
0.5.11 + mingw32 still does not support 2.1 and 2.2. Worth reopening it? @okahashi117

**Comment by okahashi117** [comment]
You mean that it is not good 'gem install msgpack --platform=ruby' to use 0.5.11 ?

**Comment by nahi** [comment]
Thanks for the workaround in the original post, but yes, we need either of followings I think:
* support 2.1 and 2.2 because we have no way to specify --platform=ruby in bundler
* drop msgpack-ruby-x86-mingw32 gem so that users can prepare cross-comiling environment to get it work

**Comment by okahashi117** [comment]
OK, I reopen it.

**Comment by tagomoris** [comment]
`v0.5.12` gems are now on rubygems.org, which built with ruby 2.0.0, 2.1 and 2.2.
Please try to install again, and reopen if you find any troubles.

**Comment by okahashi117** [comment]
:cool:

**Comment by duhaime** [comment]
Hi, I have Ruby 2.1 and can `gem install msgpack` fine, but I get an error on import:

<pre><code>C:\Users\dduhaime>gem install msgpack
Successfully installed msgpack-0.6.0-x64-mingw32
Parsing documentation for msgpack-0.6.0-x64-mingw32
Done installing documentation for msgpack after 0 seconds
1 gem installed

C:\Users\dduhaime>ruby -e "require 'msgpack'"
C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': 126: The specified module could not be found.   - C:/Ruby21-x64/lib/ruby/gems/
ingw32/lib/msgpack/msgpack.so (LoadError)
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/msgpack-0.6.0-x64-mingw32/lib/msgpack.rb:11:in `rescue in <top (required)>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/msgpack-0.6.0-x64-mingw32/lib/msgpack.rb:8:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby21-x64/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from -e:1:in `<main>'</code></pre>
