### ISSUE TITLE
Unpack strings to ASCII-8Bit, not UTF-8

### ISSUE THREAD

**Issue by paddor** [msgpack/msgpack-ruby#40]
MessagePack doesn't know the encoding of any String in a message serialized with MessagePack. Some of the Strings might be byte arrays (since there's no real distinction between Strings and byte arrays in MessagePack), and those will cause problems later when the wrongly-encoded Strings are used where a correct encoding is expected.

I suggest you set the encoding of unpacked Strings to ASCII-8Bit (`Encoding::ASCII_8BIT`). Users of this library who expect a String (not a byte array) will have to use `String#force_encoding` because only they know what unpacked Strings have which encoding.

**Comment by funny-falcon** [comment]
But they can do `#force_encoding` with UTF-8 strings too, if they know that string in different encoding.
So what's the difference?

**Comment by paddor** [comment]
Yes they can, of course, after getting an `invalid byte sequence` exception. Since msgpack-ruby really can't know a String's encoding, I still suggest using the most basic encoding possible, which is `Encoding::ASCII_8BIT`.

**Comment by iconara** [comment]
Yes #45, sorry. That’s good. Now, if I only can get you to switch to JRuby, your problem will be solved…

**Comment by paddor** [comment]
Why switch to JRuby? Does that pull request only work for JRuby or what? And don't worry, my problem is solved/worked-around already. Just an inconvenience I noticed and thought could be improved. Pretty sure the 'bin' type in MsgPack didn't exist back then yet.

**Comment by iconara** [comment]
I just meant that the semantics proposed in #44/#45 are already implemented in [msgpack-0.5.10-java](https://rubygems.org/gems/msgpack/versions/0.5.10-java), but not in the MRI release of the same version.

**Comment by paddor** [comment]
Oh okay. No need to rush with that.

**Comment by tagomoris** [comment]
I believe that `v0.5.12` solved this issue. Please reopen if any problems exist for you :)

**Comment by tagomoris** [comment]
`v0.6.0` released, which supports encoding between bin types and ASCII-8BIT string.
I believe that it solved this issue.
Please reopen if any problems exist.
