### ISSUE TITLE
MsgPack-Ruby library missing support for Binary data type 

### ISSUE THREAD

**Issue by mattheworiordan** [msgpack/msgpack-ruby#44]
I am using MsgPack to encode & decode strings and binary objects across different languages, and I see that the Ruby library makes no attempt to handle binary data according to the Ruby convention of using ASCII-8BIT encoding on byte arrays as strings.

For example:
```ruby
binary_base64 = 'HO4cYSP8LybPYBPZPHQOtuD53yrD3YV3NBoTEYBh4U0N1QXHbtkfsDfTspKeLQFt'
binary_source = Base64.decode64(binary_base64)
binary_source.encoding # => #<Encoding:ASCII-8BIT>

binary_packed = MessagePack.pack(binary_source)
binary_packed.encoding # => #<Encoding:ASCII-8BIT>
binary_unpacked = MessagePack.unpack(binary_packed)

# Now this is where things go wrong, the unpacked encoding is UTF-8, not the original ASCII-8BIT
binary_unpacked.encoding # => #<Encoding:UTF-8>

# Source binary data and unpacked binary data are now not the same
binary_unpacked == binary_source # => false
```

The problem I have is that unless I now attach metadata to the MsgPack payload that indicates whether it is a String (UTF-8) or Binary, my client libraries have no idea how to provide the data back to the consumer of our API i.e. as UTF-8 or ASCII-8BIT. 

@frsyuki, what do you suggest should be done as right now this is unfortunately a blocker for me as I cannot handle binary data for our developer customers?  It would be really appreciated to get your thoughts on this as I need to either work around this issue, attempt to fix this myself, or simply not support binary for our customers at this point which would be disappointing.

PS. The issue https://github.com/msgpack/msgpack-ruby/issues/40 is somewhat related, however it is suggesting all strings are set to ASCII-8BIT by default, whereas I believe the library should detected ASCII-BIT encodings and use the [MsgPack bin format](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family), and for all other encodings it should continue as is and use the [MsgPack string format](https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family).

**Comment by jamielennox** [comment]
This is catching me as well. I'm sending encrypted binary data within msgpack and the string encoding is messing this up. If i base64 encode then it works however if i was ok with 4x size i wouldn't be using msgpack.

**Comment by nathany** [comment]
@jamielennox Use `gem "msgpack-ably"` for now.

**Comment by jamielennox** [comment]
unfortunately i'm distributing via rpm and so i can't install a fork with the same name. It appears that the fork is exactly the same with the associated pull request merged.

**Comment by nathany** [comment]
:frowning: Looks like #45 is waiting on a response from @iconara.

**Comment by iconara** [comment]
Hey guys, I understand you're frustrated but I'm the JRuby guy, and can't really do anything about the situation. I'm really just a contributor and don't run the project. The JRuby version of the gem already works the way you want, but I know that's not really any consolation.

**Comment by nathany** [comment]
@iconara Thanks for the reply. I'm happy to use the fork for now.

**Comment by mattheworiordan** [comment]
> unfortunately i'm distributing via rpm and so i can't install a fork with the same name. It appears that the fork is exactly the same with the associated pull request merged.

@jamielennox I'll see if I can get a different version out in the next few days which addresses this problem

**Comment by tagomoris** [comment]
I've just released `v0.6.0pre1` (and `v0.6.0pre1-java`) with fixes for this issue.
Can you test this release folks? @mattheworiordan @nathany

**Comment by nathany** [comment]
I tested v0.6.0pre1 and it worked perfectly. Thanks @tagomoris

**Comment by tagomoris** [comment]
@nathany Great to hear that.
I'll release `v0.6.0` next week if no trouble reports exist.

**Comment by jamielennox** [comment]
Unfortunately i'm travelling and won't have time to test it out before release. I really appreciate you looking into it though. Thanks.

**Comment by tagomoris** [comment]
v0.6.0 released, which supports encoding between bin types and ASCII-8BIT string.
I believe that it solved this issue.
Please reopen if any problems exist.

**Comment by nathany** [comment]
Thanks!
