### ISSUE TITLE
JRuby's ExtensionValue, can't access `type` and `payload`

### ISSUE THREAD

**Issue by ramonmaruko** [msgpack/msgpack-ruby#55]
Is this intended? How do I access the `type` and `payload` properly in Ruby code?

cc @iconara

**Comment by iconara** [comment]
If I remember correctly it's not a finished feature. The JRuby version of msgpack-ruby was in a transition from the old API and old MessagePack standard to the API msgpack-ruby has now and the new MessagePack standard when it got merged in, and I haven't had any time to complete that transition.

If you're using MessagePack extensions and have the time we would be happy to see a PR that adds accessors for `type` and `payload` to `ExtensionValue`. It wouldn't hurt with a few tests around encoding and decoding extensions too.

**Comment by ramonmaruko** [comment]
I'll try to add that to JRuby when I have free time. I already submitted a pull request #14 with a few tests; but only for MRI for now.

**Comment by iconara** [comment]
That would be great, thank you.

**Comment by tagomoris** [comment]
#84 already solved this issue.
