### ISSUE TITLE
RangeError: bignum too big to convert into `unsigned long long'

### ISSUE THREAD

**Issue by Micka33** [msgpack/msgpack-ruby#57]
Using `msgpack-0.5.11`, here is the error I get:

```
irb(main):002:0> {"n"=>81669062298108866050539035482603516879}.to_msgpack
RangeError: bignum too big to convert into `unsigned long long'
	from (irb):2:in `to_msgpack'
	from (irb):2
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**Comment by ramonmaruko** [comment]
Based on the [latest spec](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-int), the largest number that we could serialize as an integer right now is 2<sup>64 − 1</sup>.

**Comment by iconara** [comment]
I'm closing this since it looks like things are working as expected, although perhaps not as you'd want them to. Feel free to open this issue again if you feel that some action needs to be taken.

**Comment by parkr** [comment]
I just hit this again migrating some code to Ruby 2.4.0 and passing `Integer` through to msgpack.

**Comment by markusschaber** [comment]
It's missing in the MsgPack spec (see https://github.com/msgpack/msgpack/issues/206), and thus msgpack-ruby cannot do anything without violating the spec. :-(
