### ISSUE TITLE
No tag for the v0.5.12 release

### ISSUE THREAD

**Issue by iconara** [msgpack/msgpack-ruby#65]
There's not tag for the v0.5.12 release.

**Comment by tagomoris** [comment]
Yes, but it's just for mingw32 gem (w/ 2.0.0, 2.1.5, 2.2.2 pre-compiled binary) release. It is almost same with v0.5.11.
It's my mistake that v0.5.12 is not just same with v0.5.11.

**Comment by tagomoris** [comment]
Do you think that we should release v0.5.12 on same commit?

**Comment by iconara** [comment]
It's not though, the release contains #59, which doesn't affect mingw32. I think releasing a proper v0.5.12 with the same code for all releases would be better.

**Comment by tagomoris** [comment]
OK. I'll release v0.5.12 for CRuby and JRuby tomorrow (JST) in right way.
Thank you to point it out.

**Comment by tagomoris** [comment]
I've just released `v0.5.12` for all platforms!
