### ISSUE TITLE
"compatibility mode" for packer

### ISSUE THREAD

**Issue by 0xBF** [msgpack/msgpack-ruby#67]
v0.6.0 use new msgpack specification, which add str8 and binary formats. But this formats don't supported by old parsers and generated msgpack data can't be parsed by such clients.

Please, add flag for disable str8 and bin formats in packer.

**Comment by tagomoris** [comment]
@0xBF Are there any reason not to use `v0.5.x`?

**Comment by 0xBF** [comment]
how long will be 0.5.x branch supported?
At least Debian Wheezy, Ubutu 14.04 LTS, CentOS 6.x comes with msgpack-c 0.5.7 without new deserialization format.

**Comment by tagomoris** [comment]
`v0.5.x` is available as it is. If coming OS versions breaks anything, it will not works well...
Anyway, patches are welcome for optional packer feature.

**Comment by iconara** [comment]
This is what the [MessagePack specification](https://github.com/msgpack/msgpack/blob/master/spec.md#impl-upgrade) has to say on the subject:

> At the same time, serializers should offer "compatibility mode" which doesn't use bin format family and str 8 format

I will take a stab at fixing this, because I need it too. I might need help with the C implementation.

**Comment by tagomoris** [comment]
#68 and #70 are merged, and `v0.6.1` released with option `compatibility_mode: true` for Packer.
That solves this issue.
