### ISSUE TITLE
Add bits for unpacking into a canonical class name

### ISSUE THREAD

**Issue by florf** [msgpack/msgpack-ruby#80]
**Purpose**
Allow a serialized object to declare its type through a two-part signature.  When the header byte is encountered by the Decoder, a new instance of the declared class is created.

**Objective**
Should this be possible, it would allow objects to serialize themselves by encapsulating their initialization parameters and provide a built-in parity to the `JSON.load()` method from the JSON gem.

Psuedo-code implementation would be something along the lines of:

```
if high nibble (outer) is 0x0:
    define className as UTF8 string of indicated length
    if low nibble is 0x1:
        payload is the immediately following Hash
    else if low nibble is 0x2:
        payload is the immediately following Array
    define clazz as the class or module identified by canonical class name className
    initialize a new instance using the payload (splat it if it's an Array)
```

**Results**
Ultimately the objective would be:

```ruby
require 'msgpack'

# Demo is a class that implements a custom .to_msgpack() method
msg = Demo.new( 1, 2, 3 ).to_msgpack
obj = MessagePack.unpack( msg ) # => a new Demo instance initialized with arguments: 1, 2, 3
```

**Comment by tagomoris** [comment]
This proposal can be implemented with ext types.
