### ISSUE TITLE
Make exception behavior of Unpacker consistent to throw only UnpackerError

### ISSUE THREAD

**Issue by frsyuki** [msgpack/msgpack-ruby#85]
As #83 points out, Unpacker throws TypeError, which doesn't extend UnpackerError.
It would be confusing if Unpacker throws an error which is not UnpackerError in terms of its naming.
Possible solutions are...:

* a) change TypeError to extend UnpackerError
* b) change TypeError to be Module. And create UnexpectedTypeError which includes TypeError and extends UnpackerError.

**Comment by tagomoris** [comment]
#86 solved this issue.
