### ISSUE TITLE
Serialized strings greater than 256 bytes fail with EOFError

### ISSUE THREAD

**Issue by ki4jnq** [msgpack/msgpack-ruby#99]
Hey, Guys,

I've been looking to replace some existing Marshal code with MsgPack. But have been running into an issue when trying to serialize extended types.  If the serialized string is longer than 256 bytes, it will fail to unpack. I discovered the issue while working with some ActiveRecord, but I have reduced it to the following repeatable example.  I am running MRI v1.9.3-p551 on Ubuntu 14.04

```ruby
require 'msgpack'

class T
  def initialize(l)
    @l = l
  end

  def to_msgpack(packer=nil)
    packer ||= MessagePack::Packer.new
    packer.pack 'a'*@l
  end

  def self.from_msgpack(mp)
    MessagePack.unpack(mp.force_encoding("ASCII-8BIT"))
  end
end

MessagePack::DefaultFactory.register_type(0x01, T, packer: :to_msgpack, unpacker: :from_msgpack)

# This works
t1 = T.new(252)
s1 = MessagePack.pack t1
# s1 = "\xC7\xFE\x01\xD9\xFCaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
puts s1.length
# => 257
r1 =  MessagePack.unpack s1

# This fails
t2 = T.new(253)
s2 = MessagePack.pack t2
# s2 = "\xC8\x00\xFF\x01\xD9\xFDaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
puts s2.length
# => 259
r2 =  MessagePack.unpack s2
```

This only happens with application extended types, large vanilla arrays don't seem to have any issues.  I've spent all day banging my head on it and haven't been able to come up with anything. any help would be much appreciated.

Thanks!

**Comment by ki4jnq** [comment]
Sorry, the exact error is:

```
EOFError: end of buffer reached
        from (irb):28:in `unpack'
        from (irb):28
        from /home/andy/.rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'
```

**Comment by tagomoris** [comment]
@ki4jnq How it works if you don't use method names `:to_msgpack` and `from_msgpack` for ext types?
These names are method names for default msgpack encoding/decoding (not ext type).
I want to know clearly whether your problem is about ext type or not.

FYI: Ruby 1.9.3 is now out of support of Ruby, and msgpack-ruby too. Please use newer Ruby. (If your bug is only for ruby 1.9.3, I will NOT fix it.)

**Comment by frsyuki** [comment]
This seems a bug. It looks unexpected to use to_msgpack/from_msgpack but it's not related.

**Comment by frsyuki** [comment]
I fixed at #100.

**Comment by tagomoris** [comment]
I'll release 0.7.1 after confirmation of CI green.

**Comment by tagomoris** [comment]
`v0.7.1` released with fix for this case. Please reopen if something goes wrong.

**Comment by ki4jnq** [comment]
@frsyuki @tagomoris Thanks, Guys! That nailed it!
